### ISSUE TITLE
Building on LInux

### ISSUE THREAD

**Issue by andy5995** [rickparrish/LORD2#2]
I'd like to build this on Debian 8 Linux, but I've never worked with C# before. Would you be willing to give me a little help to get me started?

Is there a package you'd recommend that will install the necessary C# development tools?

**Comment by rickparrish** [comment]
Sorry, I do all my development on Windows so I'm not sure.  I briefly looked at MonoDevelop in the past, but did not use it for anything more than a simple Hello World project, so I don't know if it'll be able to compile the project directly or if changes will be required.

**Comment by andy5995** [comment]
Thanks for the reply @rickparrish . I understand that you may not be able give me support on this.

Here are the build instructions for Debian Linux 8 (not yet complete)

1. I installed mono-mcs and then monodevelop from the Debian repo using apt-get.

2. I opened monodevelop and loaded LORD2/LORD2.csproj

3. At the top, I selected Debug -> Build LORD2

4. I got a message about a referenced project that wasn't found ([RMLib](https://github.com/rickparrish/RMLib))

5. I cloned the RMLib repo and tried building that (RMLib.csproj)

This is where I'm at now; attached is the build output of both projects.
[debian-linux_monodevelop_20160915_01.zip](https://github.com/rickparrish/LORD2/files/475350/debian-linux_monodevelop_20160915_01.zip)
